# Generated by Django 4.1.3 on 2023-12-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodrecipeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrecipe',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
